### ISSUE TITLE
import同级文件的时候出错

### ISSUE THREAD

**Issue by Yeafun** [ahangchen/GDLnotes#11]
### [存在疑问的文件]()
cnn_board
### 实际的效果
编译时出现问题
"D:\Deep Learning\Anaconda3\python.exe" D:/tmp/tensorflow/GDLnotes-master/src/convnet/cnn_board.py
Traceback (most recent call last):
  File "D:/tmp/tensorflow/GDLnotes-master/src/convnet/cnn_board.py", line 6, in <module>
    from convnet.conv_mnist import maxpool2d
ModuleNotFoundError: No module named 'convnet'

Process finished with exit code 1
### 在这个问题上你的做过的尝试，有什么样的思路
别的文件也出现过类似的问题，应该不是代码的原因
### 希望得到怎样的帮助，哪方面的提示
求指点

**Comment by ahangchen** [comment]
如果使用pycharm，需要把src目录设置为source directory，如果直接命令行运行，需要cd到src目录下

**Comment by Yeafun** [comment]
这个问题解决了！但是新的报错：No module named 'cPickle'  百度上说https://zhidao.baidu.com/question/457256852.html 这就是旧版的接口，但是并不能直接改名字，应该怎么办？

**Comment by ahangchen** [comment]
你用python3的话可以直接改成import pickle，我用的是python2

**Comment by Yeafun** [comment]
新问题：TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64   请问我需要继续改代码么？还是说降低python版本比较好，我现在用的3.6

**Comment by ahangchen** [comment]
跟我的python版本不同是有可能出现各种问题的，但新的这个问题可能是Tensorflow版本的兼容问题，当前的代码是在Tensorflow 1.2rc上编译过的

**Comment by Yeafun** [comment]
我的版本是1.2.1，好像tensorflow不支持版本切换，请问除了重装还有别的办法么？虽然今天没能运行成功，但是解决了我好多实际问题，非常感谢！

**Comment by ahangchen** [comment]
那就改对应的变量类型就好，具体要看你是哪个变量的类型不对应

**Comment by Yeafun** [comment]
你好，我想请教在多个GPU的情况下，tensorflow是不是会自动进行优化，不需要我指定GPU去分配任务？还有一个问题就是K80适合深度学习么？为什么我运算的时候速度还不如980？

**Comment by ahangchen** [comment]
会自动分配，K80是精度高，但是速度慢
- CUDA compute capability对比
  - GTX Titan x ：5.2
  - GTX 980      ：5.2
  - Tesla K80    ：3.7
  - Tesla K40    ：3.5
  - K4200         ： 3.0
