### ISSUE TITLE
请问训练文本相似度包括数字吗？

### ISSUE THREAD

**Issue by guandeng** [ahangchen/GDLnotes#13]
有一部分银行账号（看不出相似规则） 每家银行的账号都没有固定格式    现在想会员前台输入账号就能识别是什么银行的  这种怎么实现呢 我看很多教程用到文本相似度 word2vec 都是识别文本的 那数字这类的怎么识别呢

**Comment by ahangchen** [comment]
文本相似度需要用上下文，不太适合银行账号，银行账号应该是有一定规则的，还是应该从发现规则出发去做
